---
- hosts: kubernetes
  remote_user: root
  tasks:
    - name: install rhel epel-release
      yum:
        name: epel-release
    - name: install the ntfs disk driver
      yum:
        name: ntfs-3g
    - name: make directory to mount ntfs drive
      file: 
        path: /disk1
        state: directory
        mode: '0755'
    - name: list all drives
      command: parted -l
    - name: mount the file system
      mount:
        path: /disk1
        src: /dev/sda1
        opts: default
        state: mounted
        fstype: ext4

    - name: Add mounts to the fstab for the block device
      lineinfile:
        path: /etc/fstab
        line: UUID=c04fa2cb-71cd-40d0-baaa-8b2bc7cd70cf /disk1  ext4    defaults        1 1
        create: yes

    - name: Add nfs mounts to the fstab for the server
      lineinfile:
        path: /etc/exports
        line: /disk1              10.176.80.0/24(rw,insecure,sync,no_subtree_check,no_root_squash)
        create: yes

    - name: check the mounted directory
      command: df -h
    - name: list the mounted directory
      command: ls /disk1

# https://www.techotopia.com/index.php/Adding_a_New_Disk_Drive_to_a_CentOS_System
# https://www.howtoforge.com/tutorial/mount-ntfs-centos/
# mkdir /disk1
# mount -t ntfs-3g /dev/sdb1 /disk1
# vi /etc/fstab
# And add the line:
# /dev/sdb1 /disk1 ntfs-3g defaults 0 0
