---
- hosts: kubernetes
  remote_user: root
  tasks:
    - name: install nfs-utils
      yum:
        name: nfs-utils
    - name: make directory to mount nfs drive
      file: 
        path: /mnt/nfs/home
        state: directory
        mode: '0755'
        # owner: nfsnobody:nfsnobody
    - name: make directory to mount nfs drive
      file: 
        path: /mnt/nfs/var
        state: directory
        mode: '0755'
    - name: Start service nfs-server, if not started
      service:
        name: nfs-server
        state: started

    - name: Enable service nfs-server, and not touch the state
      service:
        name: nfs-server
        enabled: yes

    # - name: check the mounted directory
    #   command: 
    #     cmd: mount --bind /home /mnt/nfs/home | /bin/true
    #     warn: false

    # - name: check the mounted directory
    #   command: 
    #     cmd: mount --bind /mnt/nfs /mnt/nfs/var | /bin/true
    #     warn: false

    # sudo mount --bind /home /mnt/nfs/home
    # sudo mount --bind /mnt/nfs /mnt/nfs/var

    # sudo vi /etc/fstab
    # /home         /mnt/nfs/home none   bind   0   0
    # /mnt/nfs      /mnt/nfs/var  none   bind   0   0

    # - name: export the directories for nfs
    #   nfs_exports: { "/home *(rw,sync,no_root_squash)" }
    # sudo vi /etc/exports

    # /mnt/nfs            10.176.80.0/24(rw,sync,no_root_squash,no_subtree_check,crossmnt,fsid=0)
    # /mnt/nfs/home       10.176.80.0/24(rw,sync,no_root_squash,no_subtree_check)
    # /mnt/nfs/var        10.176.80.101/24(rw,sync,no_subtree_check)

    - name: export nfs directories
      command: exportfs -a

    - name: check the mounted directory
      command: df -h

# https://linuxize.com/post/how-to-install-and-configure-an-nfs-server-on-centos-8/
# https://www.howtoforge.com/tutorial/setting-up-an-nfs-server-and-client-on-centos-7/