---
- hosts: worker-37ca16, worker-e21b7d, worker-2194b5
  remote_user: root
  tasks:
    - name: install nfs-utils
      yum:
        name: nfs-utils

    - name: make directory to mount nfs drive
      file: 
        path: /mnt/nfs
        state: directory
        mode: '0755'

    - name: check the mounted directory
      shell: 
        cmd: mount -t nfs -o vers=4 kubernetes:/mnt/nfs /mnt/nfs | /bin/true
        warn: false

    - name: check the mounted directory
      shell: 
        cmd: mount -t nfs -o vers=4 kubernetes:/disk1 /disk1 | /bin/true
        warn: false

    # - name: mount the directories for nfs
    #   /etc/fstab: { "/home *(rw,sync,no_root_squash)" }
    # kubernetes:/mnt/nfs /mnt/nfs nfs defaults,timeo=900,retrans=5,_netdev   0 0
    # kubernetes:/disk1 /mnt/nfs/disk1 nfs defaults,timeo=900,retrans=5,_netdev   0 0

    - name: Add nfs mounts to the fstab for the client
      lineinfile:
        path: /etc/fstab
        line: kubernetes:/mnt/nfs /mnt/nfs nfs defaults,timeo=900,retrans=5,_netdev   0 0
        create: yes
    - name: Add nfs mounts to the fstab for the client
      lineinfile:
        path: /etc/fstab
        line: kubernetes:/disk1 /disk1 nfs defaults,timeo=900,retrans=5,_netdev   0 0
        create: yes

    - name: check the mounted directory
      command: df -h


# https://www.howtoforge.com/tutorial/setting-up-an-nfs-server-and-client-on-centos-7/

##Client side
# mkdir -p /mnt/nfs/
# mkdir -p /disk1
# Afterwards, we can mount them as follows:
# mount kubernetes:/mnt/nfs /mnt/nfs
# You should now see the two NFS shares in the outputs of
# df -h