---
- hosts: kubernetes
  remote_user: root
  tasks:
    - name: install nfs-utils
      yum:
        name: nfs-utils

    - name: make directory to mount nfs drive
      file: 
        path: /mnt/nfs
        state: directory
        mode: '0755'

    - name: Start service nfs-server, if not started
      service:
        name: nfs-server
        state: started

    - name: Enable service nfs-server, and not touch the state
      service:
        name: nfs-server
        enabled: yes

    - name: check the mounted directory
      command: 
        cmd: mount --bind /home /mnt/nfs | /bin/true
        warn: false

    - name: make directory to mount nfs drive
      file: 
        path: /mnt/nfs/disk1
        state: directory
        mode: '0755'

    - name: link block device to the nfs mount
      command: 
        cmd: mount --bind /disk1 /mnt/nfs/disk1
        warn: false

    # sudo vi /etc/fstab
    # /disk1    /mnt/nfs/disk1  bind   0   0

    - name: Add nfs mounts to the fstab for the server
      lineinfile:
        path: /etc/fstab
        line: /disk1 /mnt/nfs/disk1 none bind 0 0
        create: yes

    # - name: export the directories for nfs
    #   nfs_exports: { "/home *(rw,sync,no_root_squash)" }
    # sudo vi /etc/exports
    # /mnt/nfs            10.176.80.0/24(rw,sync,no_root_squash,no_subtree_check,cros,fsid=0)
    - name: Add nfs mounts to the exports for the server
      lineinfile:
        path: /etc/exports
        line: /mnt/nfs            10.176.80.0/24(rw,sync,no_subtree_check)
        create: yes
    - name: Add nfs mounts to the exports for the server
      lineinfile:
        path: /etc/exports
        line: /disk1            10.176.80.0/24(rw,sync,no_subtree_check)
        # (rw,root_squash,no_wdelay)
        create: yes
    - name: export nfs directories
      command: exportfs -a

    - name: check the mounted directory
      command: df -h

# https://linuxize.com/post/how-to-install-and-configure-an-nfs-server-on-centos-8/
# https://www.howtoforge.com/tutorial/setting-up-an-nfs-server-and-client-on-centos-7/